version: '3.8'
services:
  vprodb:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: vprodb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: vprodbpass
      MYSQL_DATABASE: accounts

  vproapp:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: vproapp
    ports:
      - "8080:8080"
    depends_on:
      - vprodb

  vprocache01:
    image: memcached:latest
    container_name: vprocache01
    ports:
      - "11211:11211"

  vprocache02:
    image: memcached:latest
    container_name: vprocache02
    ports:
      - "11212:11211"

  vpromq01:
    image: rabbitmq:3-management
    container_name: vpromq01
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest