version: '3.8'
services:
  vprodb:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: vprodb:latest
    container_name: vprodb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: vprodbpass
      MYSQL_DATABASE: accounts
    networks:
      - vprodbnet

  vproapp:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: vproapp:latest
    container_name: vproapp
    ports:
      - "8080:8080"
    depends_on:
      - vprodb
    networks:
      - vproappnet
      - vprodbnet

  vprocache01:
    image: memcached:latest
    container_name: vprocache01
    ports:
      - "11211:11211"
    networks:
      - vproappnet

  vprocache02:
    image: memcached:latest
    container_name: vprocache02
    ports:
      - "11212:11211"
    networks:
      - vproappnet

  vpromq01:
    image: rabbitmq:3-management
    container_name: vpromq01
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - vproappnet

  vproesearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: vproesearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9201:9200"
      - "9301:9300"
    networks:
      - vproappnet

  vprosearch01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.22
    container_name: vprosearch01
    environment:
      - discovery.type=single-node
      - cluster.name=vprofile
      - node.name=vprofilenode
      - network.host=0.0.0.0
      - http.port=9200
      - transport.port=9300
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - vproappnet

networks:
  vproappnet:
  vprodbnet: