 # scheduled on a separate node, use taints and tolerations, node affinity, or nodeSelector below.
# This strategy ensures that the workload is scheduled on a dedicated node by using taints and tolerations, node affinity, or nodeSelector.
# 
# Use:
# - Taints and tolerations prevent other pods from being scheduled on the node unless they tolerate the taint, ensuring exclusive or controlled access.
# - Node affinity and nodeSelector allow targeting specific nodes based on labels, ensuring the workload runs on nodes with desired characteristics.
#
# Advantage:
# - Provides workload isolation, improving security and performance.
# - Enables resource guarantees and reduces contention with other workloads.
# - Facilitates compliance with hardware, licensing, or operational requirements.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vproapp-db
  template:
    metadata:
      labels:
        app: vproapp-db
    spec:
      containers:
        - name: vproapp-db
          image: akhilmylaram/vprofile-db:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: myconfig
                  key: database
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - 127.0.0.1
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - 127.0.0.1
            initialDelaySeconds: 10
            periodSeconds: 5
          securityContext:
            runAsNonRoot: true
            runAsUser: 999  # MySQL official image uses 999
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc
