# MySQL Exporter Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter
  namespace: monitoring
  labels:
    app: mysql-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-exporter
  template:
    metadata:
      labels:
        app: mysql-exporter
    spec:
      containers:
      - name: mysql-exporter
        image: prom/mysqld-exporter:latest
        ports:
        - containerPort: 9104
        env:
        - name: DATA_SOURCE_NAME
          value: "root:admin123@tcp(vprodb.default.svc.cluster.local:3306)/"
        args:
        - --collect.info_schema.processlist
        - --collect.info_schema.innodb_metrics
        - --collect.info_schema.tablestats
        - --collect.info_schema.tables
        - --collect.info_schema.userstats
        - --collect.engine_innodb_status
---
# MySQL Exporter Service
apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter
  namespace: monitoring
  labels:
    app: mysql-exporter
spec:
  ports:
  - port: 9104
    targetPort: 9104
    name: metrics
  selector:
    app: mysql-exporter
---
# ServiceMonitor for MySQL Exporter
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql-exporter-monitor
  namespace: monitoring
  labels:
    app: mysql-exporter
spec:
  selector:
    matchLabels:
      app: mysql-exporter
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
---
# ServiceMonitor for VProfile App
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vproapp-monitor
  namespace: monitoring
  labels:
    app: vproapp
spec:
  selector:
    matchLabels:
      app: vproapp
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: "8080"
    path: /actuator/prometheus
    interval: 30s