apiVersion: v1
kind: Service
metadata:
  name: vproapp
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30002
      protocol: TCP
  type: NodePort
  selector:
    app: vproapp
    