apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - alertmanager-service.monitoring.svc.cluster.local:9093
    scrape_configs:
    - job_name: 'kubernetes-pods'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
    - job_name: 'node-exporter'
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - monitoring
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: node-exporter
    - job_name: 'kube-state-metrics'
      static_configs:
      - targets: ['kube-state-metrics.monitoring.svc.cluster.local:8080']
    - job_name: 'vprofile-app'
      kubernetes_sd_configs:
      - role: service
        namespaces:
          names:
          - default
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: vprofile.*app.*
      - source_labels: [__meta_kubernetes_service_port_name]
        action: keep
        regex: http
      metrics_path: /actuator/prometheus
    - job_name: 'mysql'
      kubernetes_sd_configs:
      - role: service
        namespaces:
          names:
          - default
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: vprofile.*db.*
      - source_labels: [__meta_kubernetes_service_port_name]
        action: keep
        regex: mysql
      metrics_path: /metrics